// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBanDTDD.Data;

#nullable disable

namespace QuanLyBanDTDD.Migrations
{
    [DbContext(typeof(QLBDTDTDbContext))]
    [Migration("20260423082507_XoaBangHoanTien")]
    partial class XoaBangHoanTien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyBanDTDD.Data.BaoHanh", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("ChiPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ChiTietHoaDonBanID")
                        .HasColumnType("int");

                    b.Property<string>("KetQuaXuLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LoiDoKhach")
                        .HasColumnType("bit");

                    b.Property<string>("LoiKhachBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraThucTe")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoIMEI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("ChiTietHoaDonBanID");

                    b.HasIndex("SoIMEI");

                    b.ToTable("BaoHanh");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.ChiTietHoaDonBan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoaDonBanID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKichHoat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhienBanSanPhamID")
                        .HasColumnType("int");

                    b.Property<string>("SoIMEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonBanID");

                    b.HasIndex("PhienBanSanPhamID");

                    b.ToTable("ChiTietHoaDonBan");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.ChiTietHoaDonMua", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoaDonMuaID")
                        .HasColumnType("int");

                    b.Property<int?>("PhienBanSanPhamID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonMuaID");

                    b.HasIndex("PhienBanSanPhamID");

                    b.ToTable("ChiTietHoaDonMua");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.DoiTra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChiTietHoaDonBanID")
                        .HasColumnType("int");

                    b.Property<bool>("ConSeal")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HuongXuLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayDoiTra")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhuPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoIMEI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SoTienHoanLai")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ChiTietHoaDonBanID");

                    b.ToTable("DoiTra");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.HangSanXuat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("QuocGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHangSanXuat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HangSanXuat");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.HoaDonBan", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<int?>("DoiTraID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KhachDua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HoaDonBan");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.HoaDonMua", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhaCungCapID")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("NhaCungCapID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HoaDonMua");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.HasIndex("SDT")
                        .IsUnique()
                        .HasFilter("[SDT] IS NOT NULL");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.NhaCungCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.PhienBanSanPham", b =>
                {
                    b.Property<int>("IDPhienBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPhienBan"));

                    b.Property<string>("BoNho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MauSac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("IDPhienBan");

                    b.HasIndex("SanPhamID");

                    b.ToTable("PhienBanSanPham");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.SanPham", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HangSanXuat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HangSanXuatID")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NgungKinhDoanh")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThoiGianBaoHanh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("HangSanXuatID");

                    b.HasIndex("TenSP");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.TaiKhoan", b =>
                {
                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NhanVienID");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.ThanhToan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoaDonID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KhachDua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.BaoHanh", b =>
                {
                    b.HasOne("QuanLyBanDTDD.Data.ChiTietHoaDonBan", "ChiTietHoaDonBan")
                        .WithMany()
                        .HasForeignKey("ChiTietHoaDonBanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietHoaDonBan");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.ChiTietHoaDonBan", b =>
                {
                    b.HasOne("QuanLyBanDTDD.Data.HoaDonBan", "HoaDonBan")
                        .WithMany("ChiTietHoaDonBans")
                        .HasForeignKey("HoaDonBanID");

                    b.HasOne("QuanLyBanDTDD.Data.PhienBanSanPham", "PhienBanSanPham")
                        .WithMany("ChiTietHoaDonBans")
                        .HasForeignKey("PhienBanSanPhamID");

                    b.Navigation("HoaDonBan");

                    b.Navigation("PhienBanSanPham");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.ChiTietHoaDonMua", b =>
                {
                    b.HasOne("QuanLyBanDTDD.Data.HoaDonMua", "HoaDonMua")
                        .WithMany("ChiTietHoaDonMuas")
                        .HasForeignKey("HoaDonMuaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanDTDD.Data.PhienBanSanPham", "PhienBanSanPham")
                        .WithMany("ChiTietHoaDonMuas")
                        .HasForeignKey("PhienBanSanPhamID");

                    b.Navigation("HoaDonMua");

                    b.Navigation("PhienBanSanPham");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.DoiTra", b =>
                {
                    b.HasOne("QuanLyBanDTDD.Data.ChiTietHoaDonBan", "ChiTiet_HoaDonBan")
                        .WithMany()
                        .HasForeignKey("ChiTietHoaDonBanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTiet_HoaDonBan");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.HoaDonBan", b =>
                {
                    b.HasOne("QuanLyBanDTDD.Data.KhachHang", "KhachHang")
                        .WithMany("HoaDonBans")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanDTDD.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDonBans")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.HoaDonMua", b =>
                {
                    b.HasOne("QuanLyBanDTDD.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("HoaDonMua")
                        .HasForeignKey("NhaCungCapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanDTDD.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDonMuas")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.PhienBanSanPham", b =>
                {
                    b.HasOne("QuanLyBanDTDD.Data.SanPham", "SanPham")
                        .WithMany("PhienBanSanPham")
                        .HasForeignKey("SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.SanPham", b =>
                {
                    b.HasOne("QuanLyBanDTDD.Data.HangSanXuat", null)
                        .WithMany("SanPham")
                        .HasForeignKey("HangSanXuatID");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyBanDTDD.Data.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QuanLyBanDTDD.Data.TaiKhoan", "NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.HangSanXuat", b =>
                {
                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.HoaDonBan", b =>
                {
                    b.Navigation("ChiTietHoaDonBans");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.HoaDonMua", b =>
                {
                    b.Navigation("ChiTietHoaDonMuas");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.KhachHang", b =>
                {
                    b.Navigation("HoaDonBans");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.NhaCungCap", b =>
                {
                    b.Navigation("HoaDonMua");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.NhanVien", b =>
                {
                    b.Navigation("HoaDonBans");

                    b.Navigation("HoaDonMuas");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.PhienBanSanPham", b =>
                {
                    b.Navigation("ChiTietHoaDonBans");

                    b.Navigation("ChiTietHoaDonMuas");
                });

            modelBuilder.Entity("QuanLyBanDTDD.Data.SanPham", b =>
                {
                    b.Navigation("PhienBanSanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
